// =========================
// Multiplayer protocol types
// =========================
// Shared between the browser client (roomClient/host/guest) and the relay
// server. The server only uses the connection-management messages
// (create/join/spectate/watch/setRole/leave/lock/relay); the game payload types are
// used by clients.

import { TileKind } from "../game/assets/blocks";
import { PowerupType } from "../game/assets/powerups";
import { PlayerStats } from "../game/hooks/tracker";
import { Direction } from "./game";

// =========================
// Room / roster
// =========================

/** A participant in a room, as reported by the relay server. */
export interface RoomPlayer {
  slot: number;
  name: string;
  isHost: boolean;
}

/** A spectator in a room. Spectators watch the game but take no slot. */
export interface RoomSpectator {
  name: string;
}

/** The role a room member holds: a player takes a slot, a spectator watches. */
export type RoomRole = "player" | "spectator";

/**
 * An open lobby hosted inside the same Discord Activity instance, pushed to
 * `watch` subscribers so participants can join without a code.
 */
export interface InstanceLobby {
  code: string;
  hostName: string;
  playerCount: number;
  /** True while a match is running — joining then lands as a spectator. */
  locked: boolean;
}

/**
 * A public lobby, as listed by the relay's `browse` message — any room the
 * host didn't mark private. Sorted by latencyMs ascending before paging.
 */
export interface PublicLobby {
  code: string;
  /** Room display name — "<host>'s room" when the creator didn't set one. */
  name: string;
  hostName: string;
  /** Map preset id (src/game/maps.ts) the host declared at creation. */
  mapId: string | null;
  playerCount: number;
  /** Always 4 — a lobby is full when playerCount reaches it. */
  maxPlayers: number;
  /** Occupied player slots, for the lobby browser's colored dots. */
  slots: number[];
  /** True while a match is running — joining then lands as a spectator. */
  locked: boolean;
  /**
   * Round-trip latency between the relay and this lobby's host, measured by
   * the relay's heartbeat pings (the variable half of a guest's
   * client -> relay -> host path). Null until the first pong arrives.
   */
  latencyMs: number | null;
}

/** How a slot in the local roster is controlled. */
export type ControlKind = "local" | "remote" | "computer";

/** A slot in the host-built roster used to initialize the game. */
export interface RosterEntry {
  id: string;
  name: string;
  control: ControlKind;
  slot: number;
}

// =========================
// Server <-> client connection messages
// =========================

export type ClientToServerMessage =
  /** instanceId tags the room with its Discord Activity instance; isPublic opts the room out of the public lobby list when false (public by default); roomName (≤24) is the room's display name in the list (default "<name>'s room"); mapId names the host's declared map preset; seed marks a seeder-hosted lobby that promotes its first joiner to host and requires the relay's shared seedToken (server-side only — clients never send either). */
  | { t: "create"; name: string; instanceId?: string; isPublic?: boolean; roomName?: string; mapId?: string; seed?: boolean; seedToken?: string }
  | { t: "join"; code: string; name: string }
  | { t: "spectate"; code: string; name: string }
  /** Subscribe to one Discord instance's lobbies (never joins a room). */
  | { t: "watch"; instanceId: string }
  /** Request one page of the public lobby list (0-based page). */
  | { t: "browse"; page: number; pageSize: number }
  | { t: "setRole"; role: RoomRole }
  | { t: "leave" }
  | { t: "lock" }
  | { t: "unlock" }
  | { t: "relay"; to: "host" | "guests"; payload: GamePayload };

export type ServerToClientMessage =
  | { t: "created"; code: string; slot: number }
  | { t: "joined"; code: string; slot: number }
  | { t: "spectating"; code: string }
  | { t: "room"; code: string; players: RoomPlayer[]; spectators: RoomSpectator[]; mapId?: string | null }
  | { t: "error"; message: string }
  | { t: "hostLeft" }
  | { t: "lobbies"; lobbies: InstanceLobby[] }
  /** One page of the public lobby list, in response to `browse`. */
  | { t: "lobbyList"; lobbies: PublicLobby[]; page: number; pageSize: number; total: number }
  /** Sent to the host when a spectator joins a locked (in-progress) room. */
  | { t: "spectatorJoined" }
  | { t: "relay"; from: number; payload: GamePayload };

// =========================
// Game payloads (relayed between host and guests)
// =========================

/** Per-player input state, sent by guests to the host every change. */
export interface InputPayload {
  t: "input";
  sequence: number;
  up: boolean;
  down: boolean;
  left: boolean;
  right: boolean;
  bomb: boolean;
  /** One discrete movement generated by one physical key press. */
  move?: Direction;
}

/** Host-to-guest latency probe. */
export interface LatencyPingPayload {
  t: "latencyPing";
  id: number;
  slot: number;
}

export interface LatencyPongPayload {
  t: "latencyPong";
  id: number;
}

/** A single cell's mutable state in a snapshot. */
export interface CellSnapshot {
  /** Index of the cell in the grid (row * gridCols + col). */
  index: number;
  tile: TileKind;
  bomb: boolean;
  powerup: PowerupType | null;
}

/** A character's mutable state in a snapshot. */
export interface CharacterSnapshot {
  id: string;
  /** Highest guest input sequence processed by the host for this player. */
  lastProcessedInputSequence?: number;
  row: number;
  col: number;
  facing: Direction;
  lives: number;
  winning: boolean;
  isImmune: boolean;
  isWalking: boolean;
  isHurt: boolean;
  hasShield: boolean;
  isShieldBlock: boolean;
  isShieldExpiring: boolean;
}

/** Full authoritative state of the game at one instant, host -> guests. */
export interface SnapshotPayload {
  t: "snapshot";
  characters: CharacterSnapshot[];
  stats: PlayerStats[];
  cells: CellSnapshot[];
  timeElapsedMs: number;
}

/** Sent once by the host when the game starts, so guests can build the grid. */
export interface StartPayload {
  t: "start";
  cellTypes: TileKind[];
  roster: RosterEntry[];
}

/** Transient blast event relayed by the host for guest visuals/sound. */
export interface BlastPayload {
  t: "blast";
  cells: { row: number; col: number }[];
  reach: { up: number; down: number; left: number; right: number };
}

/** Sent by the host when the game ends so guests can show the end screen. */
export interface GameOverPayload {
  t: "gameOver";
  state: "GAME_OVER" | "WIN";
  winner?: PlayerStats;
  gameStats: import("../game/hooks/tracker").GameStats;
}

/**
 * Sent by the host when it returns to the room lobby after a match, so
 * guests can enable their own "Return to Lobby" button.
 */
export interface BackToLobbyPayload {
  t: "backToLobby";
}

export type GamePayload =
  | InputPayload
  | SnapshotPayload
  | StartPayload
  | BlastPayload
  | GameOverPayload
  | BackToLobbyPayload
  | LatencyPingPayload
  | LatencyPongPayload;
